site_name: GRACE Groundwater Subsetting Tool
site_url: https://ggst.readthedocs.io/en/latest/
site_description: This is the documentation for the GRACE Groundwater Subsetting Tool.
site_author: BYU Hydroinformatics Laboratory
repo_url: https://github.com/BYU-Hydroinformatics/GGST
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - mdx_math
    - attr_list
    - sane_lists
    - admonition
    - pymdownx.arithmatex:
        generic: true

plugins:
    - search
    - macros

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Overview: overview.md
  - Computational Algorithm: algorithm.md
  - Adding and Deleting Regions: uploading.md
  - Analysis at a Single Point: points.md
  - Application Programming Interface (API): api.md
  - The Water Table Fluctuation Method: wtf.md

extra_css:
  - css/custom.css

copyright: Copyright &copy; 2018 - 2024 Norman L. Jones, Ph.D. All rights reserved.