[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "tethysapp-ggst"
version = "0.0.1"
description = "Visualize and subset Grace data"
authors = [
    {name = "Sarva Pulla", email = "pulla@byu.edu"},
]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
include = ["tethysapp*"]

[tool.setuptools.package-data]
"*" = ["*.js", "*.css", "*.html", "*.png", "*.ico", "*.jpg", "*.gif", "*.svg", "*.json", "*.yml", "*.yaml", "*.txt", "*.xml", "*.csv", "*.geojson", "*.tif", "*.tiff"]
