site_name: BYU CCE 270
site_url: https://byu-cce270.readthedocs.io/en/latest/
site_description: Course materials for CCE 270 at BYU
site_author: Instructors and TAs of CCE 270 at BYU
repo_url: https://github.com/byu-cce270/content/
favicon: 'images/favicon.ico'
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
    - attr_list
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Unit 1:
    - A Tour of Class Resources: unit1/0_getting_started/day1_hw.md
    - Lookups, Match, and Data Validation:
        - Reading: unit1/1_lookup_match/lookmat_read.md
        - In Class: unit1/1_lookup_match/lookmat_class.md
        - Homework: unit1/1_lookup_match/lookmat_hw.md
    - Analyzing/Managing Data, Conditional Formatting:
        - Reading: unit1/2_analyzing_managing_data/data_read.md
        - In Class: unit1/2_analyzing_managing_data/data_class.md
        - Homework: unit1/2_analyzing_managing_data/data_hw.md
    - If Statements and Goal Seek:
      - Reading: unit1/3_if_goalseek/ifgs_read.md
      - In Class: unit1/3_if_goalseek/ifgs_class.md
      - Homework: unit1/3_if_goalseek/ifgs_hw.md
    - Pivot Table and Query Function:
      - Reading: unit1/4_pivot_query/pivquer_read.md
      - In Class: unit1/4_pivot_query/pivquer_class.md
      - Homework: unit1/4_pivot_query/pivquer_hw.md
    - Gantt Chart, Project Scheduling and Tracking:
        - Reading: unit1/5_gantt_charts/gantt_read.md
        - In Class: unit1/5_gantt_charts/gantt_class.md
        - Homework: unit1/5_gantt_charts/gantt_hw.md
    - Unit 1 Project:
        - Project Prompt: unit1/6_unit1_project/u1_pro_promt.md

  - Unit 2:
    - How to access course book: home/accessing_book/access_book.md
    - Introduction to Python and Variables:
      - Reading: unit2/0_intro_python_variables/into_var_read.md
      - In Class: unit2/0_intro_python_variables/into_var_class.md
      - Homework: unit2/0_intro_python_variables/into_var_hw.md
    - Introducing List:
      - Reading: unit2/1_introducing_lists/lists_read.md
      - In Class: unit2/1_introducing_lists/lists_class.md
      - Homework: unit2/1_introducing_lists/lists_hw.md
    - Working with Lists (For Loops):
        - Reading: unit2/2_for_loops_into_functions/for_read.md
        - In Class: unit2/2_for_loops_into_functions/for_class.md
        - Homework: unit2/2_for_loops_into_functions/for_hw.md
    - IF Statements:
        - Reading: unit2/3_if_statements/if_read.md
        - In Class: unit2/3_if_statements/if_class.md
        - Homework: unit2/3_if_statements/if_hw.md
    - Dictionaries:
        - Reading: unit2/4_dictionaries/dict_read.md
        - In Class: unit2/4_dictionaries/dict_class.md
        - Homework: unit2/4_dictionaries/dict_hw.md
    - While Loops:
        - Reading: unit2/5_while_loops/while_read.md
        - In Class: unit2/5_while_loops/while_class.md
        - Homework: unit2/5_while_loops/while_hw.md
    - Functions (Part 1):
        - Reading: unit2/6a_functions/functions_1_read.md
        - In Class: unit2/6a_functions/functions_1_class.md
        - Homework: unit2/6a_functions/functions_1_hw.md
    - Functions (Part 2):
      - Reading: unit2/6b_functions/functions_2_read.md
      - In Class: unit2/6b_functions/functions_2_class.md
      - Homework: unit2/6b_functions/functions_2_hw.md
